using System.Runtime.InteropServices;
using System.Text;
using Task5_6;
Console.OutputEncoding = Encoding.Unicode;
Console.InputEncoding = Encoding.Unicode;
var element = new StatefulElementNode("div", "block", "normal", new List<string>());
element.SetState(new VisibleState());
element.SetState(new HiddenState());
element.SetState(new DisabledState());
element.SetState(new VisibleState());