using System.Runtime.InteropServices;
using System.Text;
using Task5_6;
Console.OutputEncoding = Encoding.Unicode;
Console.InputEncoding = Encoding.Unicode;
var root = new LightElementNodeWithLifecycle("div", "block", "normal", new List<string>());
var child1 = new LightElementNodeWithLifecycle("p", "inline", "normal", new List<string>());
var child2 = new LightElementNodeWithLifecycle("span", "inline-block", "normal", new List<string>());
var commandManager = new CommandManager();
var addCommand1 = new AddElementCommand(root, child1);
commandManager.ExecuteCommand(addCommand1);
var addCommand2 = new AddElementCommand(root, child2);
commandManager.ExecuteCommand(addCommand2);
commandManager.UndoCommand();
var textNode = LightTextNode.GetTextNode("Hello, World!");
var addTextCommand = new AddElementCommand(child1, textNode);
commandManager.ExecuteCommand(addTextCommand);
var removeTextCommand = new RemoveElementCommand(child1, textNode);
commandManager.ExecuteCommand(removeTextCommand);
commandManager.UndoCommand();